name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --test-randomize-ordering-seed random --coverage

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          exclude: "**/main.dart **/*.g.dart **/*.gen.dart **/l10n/*.dart **/l10n/**/*.dart **/*.freezed.dart"
          path: coverage/lcov.info
          min_coverage: 100

      - name: Upload production-ready web build files
        uses: actions/upload-artifact@v2
        with:
          name: web-app-files
          path: ./build/web
