name: Build & Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --test-randomize-ordering-seed random --coverage

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          exclude: "**/main.dart **/*.g.dart **/*.gen.dart **/l10n/*.dart **/l10n/**/*.dart **/*.freezed.dart"
          path: coverage/lcov.info
          min_coverage: 100

      - name: Upload production-ready web build files
        uses: actions/upload-artifact@v2
        with:
          name: web-app-files
          path: ./build/web

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download Web artifact
        uses: actions/download-artifact@v2
        with:
          name: web-app-files
          path: ./build/web

      - name: Deploy Web to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: flutterremotely
          channelId: live
